### ISSUE TITLE
Wybrać temat 

### ISSUE THREAD

**Issue by sebkaz** [sarawaniolka/masters_thesis#1]
Najelpiej byłoby 4 ale jeśli nie będzie to za bardzo skomplikowane. 

Możemy ogólnie zrobić pracę o sposobach analizy plików dźwiękowych i sposobów ich przygotowania do analiz... może w Julii ??

**Comment by sarawaniolka** [comment]
temat: Adversarial attacks in image recognition.
Trochę poczytałam, dodałam nowy plik z notatkami i luźnymi myślami związanymi z tym tematem

**Comment by sebkaz** [comment]
ok
